// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09ebwqkAua2CcTF_4wGXcJtWn81_LIwQ',
    appId: '1:415731788617:web:8797ce1a4eb55b36d70898',
    messagingSenderId: '415731788617',
    projectId: 'message-board-app-9c0c7',
    authDomain: 'message-board-app-9c0c7.firebaseapp.com',
    storageBucket: 'message-board-app-9c0c7.firebasestorage.app',
    measurementId: 'G-2RDQ7Y4TKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLbtH4zcC6qOUO0tMaIkAxsPHAdE1UUc',
    appId: '1:415731788617:android:99b7043afeb79cc5d70898',
    messagingSenderId: '415731788617',
    projectId: 'message-board-app-9c0c7',
    storageBucket: 'message-board-app-9c0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26kLtKKcDB244VhNn1PWNThhZA-Kv0v4',
    appId: '1:415731788617:ios:9870fc5b8c49223dd70898',
    messagingSenderId: '415731788617',
    projectId: 'message-board-app-9c0c7',
    storageBucket: 'message-board-app-9c0c7.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26kLtKKcDB244VhNn1PWNThhZA-Kv0v4',
    appId: '1:415731788617:ios:9870fc5b8c49223dd70898',
    messagingSenderId: '415731788617',
    projectId: 'message-board-app-9c0c7',
    storageBucket: 'message-board-app-9c0c7.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD09ebwqkAua2CcTF_4wGXcJtWn81_LIwQ',
    appId: '1:415731788617:web:3652811ad0bb5b04d70898',
    messagingSenderId: '415731788617',
    projectId: 'message-board-app-9c0c7',
    authDomain: 'message-board-app-9c0c7.firebaseapp.com',
    storageBucket: 'message-board-app-9c0c7.firebasestorage.app',
    measurementId: 'G-71GE3EHW68',
  );

}